project_id = "kwlmdywxlyzugoxbstmg"

[functions.send-appointment-reminders]
verify_jwt = false

[functions.process-recurring-patterns]
verify_jwt = false

[functions.notify-appointment-change]
verify_jwt = false

[functions.notify-appointment-status]
verify_jwt = false

[functions.send-booking-confirmation]
verify_jwt = false

[functions.send-review-reminder]
verify_jwt = false

[functions.create-service-payment]
verify_jwt = false
